cuappdev/pollo-backend

- src/routers/Organizaitons/PostOrganizationRouter.js
- src/routers/PostLectureRouter.js
Also name/syntax changes to `PostOrganizationRouter`
Sample response:
```
{
"data": {
"node": {
"dateTime": "1000",
"id": "19"
}
},
"success": true
}
```
> Create lecture router

- src/routers/Courses/AddAdminsToCourseRouter.js
- src/routers/Courses/AddStudentsToCourseRouter.js
- src/routers/Courses/DeleteCourseRouter.js
- src/routers/Courses/PostCourseRouter.js
- src/routers/Courses/RemoveAdminsFromCourseRouter.js
- src/routers/Courses/RemoveStudentsFromCourseRouter.js
- src/routers/Courses/UpdateCourseRouter.js
- src/routers/EndLectureRouter.js
- src/routers/GetMeRouter.js
- src/routers/GoogleSignInRouter.js
- src/routers/HelloWorldRouter.js
- src/routers/Lectures/DeleteLectureRouter.js
- src/routers/Lectures/GetLiveLecturesRouter.js
- src/routers/Lectures/LecturePortsRouter.js
- src/routers/Lectures/PostLectureRouter.js
- src/routers/Lectures/UpdateLectureRouter.js
- src/routers/Organizaitons/DeleteOrganizationRouter.js
- src/routers/Organizaitons/PostOrganizationRouter.js
- src/routers/Organizaitons/UpdateOrganizationRouter.js
- src/routers/Questions/DeleteQuestionRouter.js
- src/routers/Questions/PostQuestionRouter.js
- src/routers/Questions/UpdateQuestionRouter.js
- src/routers/Responses/PostResponseRouter.js
- src/routers/StartLectureRouter.js
- src/routers/Users/GetUserCoursesRouter.js
- src/routers/Users/GetUsersRouter.js
- src/utils/AppDevEdgeRouter.js
- src/utils/AppDevNodeRouter.js
- src/utils/AppDevRouter.js
`AppDevEdgeRouter<T>` and `AppDevNodeRouter<T>` are safer because parameter `T` specifies what the router is gonna return, so when a developer extends the class the content-producing method returns the right type of content.
`AppDevRouter` doesn't do this, and so whomever extends it can return whatever they want in when they implement `content() { ... }` and can change it without signaling anywhere that there was a type change. This is very much non-ideal.
Requiring type parameters  is a common pattern, and a good one. `React.Component` has required parameters `<Props, State>` for example, to enforce type safety on the components properties and state respectively. Generally, one should try to avoid undefined, hand-wavy types.
NOTE: this is a large PR because it makes all routers return …
> Proposal: Make AppDevRouter typesafe by forcing people to define what the route will return

- .eslintrc
- src/repos/DraftsRepo.js
- src/repos/PollsRepo.js
- src/repos/QuestionsRepo.js
- src/repos/SessionsRepo.js
- src/routers/v2/JoinSessionRouter.js
- src/routers/v2/StartSessionRouter.js
- test/repos/draft.test.js
- test/repos/poll.test.js
- test/repos/question.test.js
- test/repos/userSession.test.js
- test/routes/api.draft.test.js
- test/routes/api.poll.test.js
- test/routes/api.question.test.js
- test/routes/api.session.test.js
- test/routes/api.user.test.js
- Fixed update methods since typeorm's update function didn't support updating JSON or array fields 
- Split up /start/session/ route which was originally for creating or joining a session into /start/session/ (for creating) and /join/session/ (for joining) to make logic more clear
- Small Jest tweak cause noticed that .toBeTruthy and .toBeFalsy isn't equivalent to .toBe(true) and .toBe(false)
> Fix update repo methods and clean up session routers

- src/routers/v2/JoinSessionRouter.js
Admins can use the JoinSessionRouter since this route allows everyone to connect to the session socket
> Fix error when admin was joining polls

- src/SessionSocket.js
- Makes sure any live polls are persisted before socket is closed.
- Previously, polls would be saved either when the admin ended it or a new poll was asked
> Persist polls for socket

- package-lock.json
- package.json
- src/SessionManager.js
- src/routers/v2/JoinSessionRouter.js
Initial implementation of live-session indicator caused weird behavior in `/join/session/` route, so fixed it by separating the functionality of verifying the existence and activeness of session socket.
> Fix live session indicator

- src/routers/v2/Polls/GetGroupPollsRouter.js
`/sessions/:id/polls/` will return `[]` instead of `[{}]` if no polls found
> Return empty array if no polls match group ID

- src/db/DbConnection.js
- Looks like autoSchemaSync is necessary on the development side since it needs it to initialize a blank database
- If it's in production, autoSchemaSync will be false and the migrations will run
> Fix configurations for migrations

- README.md
- src/db/DbConnection.js
The new DBs on DigitalOcean don't use port 5432 so we can use an env var in production to specify it.
> Change DB port to rely on env vars

- src/db/DbConnection.js
Another one
- DigitalOcean DBs require SSL to be enabled for production
- Don't need to run this migration anymore
> Enable SSL for prod DB

- .travis.yml
- docker_push
- Builds docker image and updates server by sshing into the dev server every time a commit is pushed to `master` (unless we want to use a dev branch or something)
Tested it on this branch. Output can be seen here:
https://travis-ci.org/cuappdev/pollo-backend/builds/495646469
> Add deploy hooks for dev server

- src/API.js
@AAAstorga wanted `/auth/refresh` route to have `api/v2/` path in front
@meganle Not sure if I could delete the original `/auth/refresh` so I just created a new route. Thoughts on whether we should keep the old one?
> Add a v2 route to refresh token

- .travis.yml
As the title says, the original syntax only recognized the first branch stated. Syntax referenced from Travis documentation
> Fix travis deploy script to support multiple branches

- package-lock.json
- package.json
- src/API.js
- src/repos/UserSessionsRepo.js
- src/routers/v1/EndPollRouter.js
- src/routers/v1/GenerateCodeRouter.js
- src/routers/v1/HelloWorldRouter.js
- src/routers/v1/Polls/DeletePollRouter.js
- src/routers/v1/Polls/GetLivePollsRouter.js
- src/routers/v1/Polls/GetPollRouter.js
- src/routers/v1/Polls/PostPollRouter.js
- src/routers/v1/Polls/UpdatePollRouter.js
- src/routers/v1/StartPollRouter.js
- src/routers/v2/APITypes.js
- src/routers/v2/Users/InitializeSessionRouter.js
- src/routers/v2/Users/RefreshSessionRouter.js
- src/utils/AppDevNodeRouter.js
- src/utils/AppDevRouter.js
- src/utils/AppDevUtils.js
- Moved auth routers to their own files
- Allows custom middleware for individual routers
- By default, routers use middleware to secure route
- V1 routers override middleware to not be secure (@aliciaxw @yuna878 We should discuss whether we need to keep v1 routes or not)
- Remove `passport` and unneeded routes
> Implement custom middleware and rewrite auth routes

- src/GroupSocket.js
Add a field `optionsWithChoices` to Poll object in sockets which contains `[{choice: 'A', option: 'blue'}, {choice: 'B', option:'red'}]` so client won't have to worry about computing the choice
> Add choices to poll object

- src/models/Base.js
- src/repos/GroupsRepo.js
- src/routers/v2/Polls/GetGroupPollsRouter.js
- test/repos/group.test.js
- test/repos/poll.test.js
- Getting polls/questions by group will be in ascending order (oldest to newest), should fix last live times bug
- Getting polls will return all polls in a group (not just shared polls), but poll results that are unshared will be hidden (set to `{}`)
- Minor variable renames and documentation updates for clarity
> Change poll/question ordering

- src/repos/GroupsRepo.js
- src/routers/v2/APITypes.js
- src/routers/v2/Groups/GetGroupRouter.js
- src/routers/v2/Groups/PostGroupRouter.js
- src/routers/v2/Groups/UpdateGroupRouter.js
- src/routers/v2/StartGroupRouter.js
- Some of the Group routes are missing `updatedAt` and `isLive` in their return values 
- The client doesn't use all of these values for some of the routes but the APIGroup type specifies them 
- For uniformity, I've added them, but we could make these fields optional. **Thoughts**?
> Fix flow errors with Groups API

- src/GroupManager.js
- src/models/Base.js
- src/models/UserSession.js
- src/repos/GroupsRepo.js
- src/routers/v2/APITypes.js
- src/routers/v2/Drafts/GetDraftsRouter.js
- src/routers/v2/Drafts/PostDraftRouter.js
- src/routers/v2/Drafts/UpdateDraftRouter.js
- src/routers/v2/Questions/GetQuestionRouter.js
- src/routers/v2/Questions/GetQuestionsRouter.js
- src/routers/v2/Questions/PostQuestionRouter.js
- src/routers/v2/Questions/UpdateQuestionRouter.js
- test/routes/api.draft.test.js
- test/routes/api.group.test.js
- test/routes/api.question.test.js
- We use the `bigint` type for timestamps in our postgres db
- However, every time we query from the database, all values in columns with type `bigint` are actually returned as a string instead of a number since javascript's number type doesn't support as large of numbers as `bigint`
- Turns out that iOS has been expecting strings for all of these timestamps
- Instead of using a `number` type for timestamps, it makes sense to just change it to string since that's consistent with postgres and iOS
> Standardize timestamps to string

- src/GroupSocket.js
- src/models/Group.js
- src/repos/GroupsRepo.js
- src/routers/v2/APITypes.js
- src/routers/v2/Groups/DeleteGroupRouter.js
- src/routers/v2/Groups/GetAdminGroupsRouter.js
- src/routers/v2/Groups/GetGroupRouter.js
- src/routers/v2/Groups/GetGroupsRouter.js
- src/routers/v2/Groups/PostGroupRouter.js
- src/routers/v2/Groups/UpdateGroupRouter.js
- src/routers/v2/JoinGroupRouter.js
- src/routers/v2/StartGroupRouter.js
- src/utils/Lib.js
- test/routes/api.group.test.js
- `Group` has two new fields, `location: { lat: ?number, long: ?number }` and `isLocationRestricted: boolean`
- new endpoint `/sessions/:id/location/restriction/` that updates a group's location restriction
- `/start/session/` initializes the group location with the admin's location (lat/long can be null)
- `/join/session/` will update the group's location if the user is an admin, or possibly throw an error if the user is a member and is not within 300 meters of the group's location
> Group location support

- src/GroupSocket.js
When returning a poll in the sockets, the poll object should have field `id` instead of `pollID`
> Change id field for poll

- src/routers/v2/Polls/GetGroupPollsRouter.js
Another one, if the user didn't answer the poll, the field `userAnswers` doesn't even appear in the response. So if a user didn't answer the poll, an empty array should be the default value.
> Fix userAnswers field when getting group polls

- src/utils/AppDevRouter.js
Middleware was already initialized and this attaches auth to all routers which it shouldn't
> Remove unnecessary middleware stuff

- src/GroupSocket.js
`count` for each `PollResult` in `answerChoices` was set to `null` in current poll when current poll should not have been updated
> Fix answerChoice mutability

- .travis.yml
- docker_push
- Weird travis syntax where it only allows a single script to run for the deploy section
- Moved the decryption of the server.pem into the docker_push script
- Tested by deploying my own branch on dev since master wasn't previously deployed
> Fix travis deploy script

- src/GroupSocket.js
- src/routers/v2/swagger.json
The `count` property of `answerChoice` in socket polls is `null` for users only for live polls. Previously, `count` was set to `null` for users for both live and ended polls.
> Include count for ended polls in socket

- src/GroupSocket.js
In a socket poll, the poll ID should be assigned to the key `id` in the `currentPoll`, but was incorrectly set to `pollID` for the event `user/poll/results`. This is fixed now.
</details>
> Change key pollID to id for event user/poll/results

- src/GroupSocket.js
- src/routers/v2/JoinGroupRouter.js
An error is occurring on socket connection where we check whether the user is an admin or not. We pass the incorrect `id` field into the repo function, resulting in `undefined` admins.
Changed `id` to `uuid`. Also removed an unneeded import.
The unit tests should still work locally, but we need to test with iOS and Android to make sure this fix isn't the only one we'll need since we've switched from `id` to `uuid`.
#233 
</details>
> Access correct ID field of group in socket

- src/GroupSocket.js
- test/repos/draft.test.js
- test/repos/poll.test.js
- test/repos/user.test.js
`SocketPoll` requires an `id` when a poll is ended or shared, but the field `uuid` was being set instead. This is fixed. In addition, various `draft` repo tests were incorrectly using `id` instead of `uuid`, resulting in tests that pass because `undefined === undefined`. 
When `id` is assigned when a poll is ended, `id` and not `uuid` should be reflected in the current poll.
Ran unit tests and tested the current iOS build with the local server.
I will continue to be on the lookout for overlooked `id` and `uuid` mishaps.
#233
> Keep currentPoll consistent with SocketPoll

- src/repos/UserSessionsRepo.js
There was an issue that sometimes would come up where a session would not have a user associated with it. I found out that this didn't happen on the first time a session is created but only when it was updated. I had iOS try out these changes and it seemed to work.
Make sure the user stayed attached to the session
I deployed on the dev server and had iOS test it out.
Make sure that this doesn't happen anywhere else.
> Fix bug with sessions and users

- package-lock.json
- package.json
- webpack.config.js
On my laptop, `npm start` would frequently fail with an `ELIFECYCLE` error. This turns out to have been because the script could occasionally leave the server running in the background, causing the port needed by the new instance to be inaccessible.
* Removed `&& node build/bundle.js` from the start script.
* Modified `webpack.config.js` to ensure proper restarts.
* Fixed typo in `npm run prod` script.
The server now runs and all tests pass on my machine. It would be great if @aliciaxw and @raahimenon could check that this branch still runs properly on macos and WSL.
> Fix webpack watching issues

- src/routers/v2/GenerateCodeRouter.js
- src/routers/v2/Groups/PostGroupRouter.js
- src/routers/v2/StartGroupRouter.js
- test/routes/api.group.test.js
Generates group code in PostGroupRouter.js and StartGroupRouter.js instead of going through GenerateCodeRouter.js.
Updated test cases to match
Removed "code" pattern match from the routers and instead replaced them with "const code = GroupsRepo.createCode();" so that users cannot input their own codes.
Removed the code variable from "opts()" in the groups router api test file and checked to see if all tests still worked; they did.
Eventually iOS, Android, and Web will want to update their code to stop calling generate code, but that is only for optimization; this shouldn't conflict with their current implementation.
> Deprecated Generate Code Router

- src/routers/v2/CSVGenerator.js
- src/routers/v2/Groups/GetCSVRouter.js
- test/routes/api.group.test.js
- Updated CSVGenerator.js for Canvas formatting
- Updated GetCSVRouter.js to output the csv when called for Canvas
- Updated api.group.test.js for Canvas formatting (as well as added one error handling test)
- added function to output a stream with necessary csv data in CSVGenerator.js
- updated function to no longer throw an error when called with canvas formatting in GetCSVRouter.js
- tested the canvas export with all the same testing situations as the cms export
> Added Canvas support to CSV exporting

- package-lock.json
- src/GroupSocket.js
- src/models/Draft.js
- src/models/Poll.js
- src/repos/GroupsRepo.js
- src/repos/PollsRepo.js
- src/routers/v2/APITypes.js
- src/routers/v2/Polls/GetGroupPollsRouter.js
- src/routers/v2/Polls/GetPollRouter.js
- src/routers/v2/Polls/UpdatePollRouter.js
- src/routers/v2/swagger.json
- src/utils/Constants.js
- test/repos/group.test.js
- test/repos/poll.test.js
- test/routes/api.group.test.js
- test/routes/api.poll.test.js
- test/socket.test.js
As a part of downsizing, various free-response related fields were removed.
the field `letter` is renamed to `index` because of the change from `string` to `int`
**API Poll**
`type` - removed
**Draft**
`options: string[]` - will no longer be empty for FR
**Poll (Types)**
`PollType` - type removed
`PollResult` - `index` is no longer optional
`PollChoice` - `index` is no longer optional
**Poll (Fields)**
`upvotes` - removed
`answerChoices: PollResult[]` - see `PollResult`
`answers: { googleID : PollChoice[] }`  - see `PollChoice`
`correctAnswer` - no behavioral changes, just won’t be empty string if FR
**SocketPoll**
`type` - removed
`upvotes` - removed
`answers` - will be `{ googleID : PollChoice }` instead of `PollChoice[]`
**ClientPoll**
`type` - removed
`upvotes` - removed
**Socket** …
> Free Response API changes

- .travis.yml
- Dockerfile.dev
- Dockerfile.prod
- docker_push
Currently, our dev server ran in production mode, meaning that dev only features are not possible. This pr adds separate `Dockerfile.dev` and `Dockerfile.prod` files to allow different features and restrictions.
Created two dockerfiles and updated travis to deploy correctly.
There was no really good way to test the travis portion of this without merging it and actually attempting to deploy. Unfortunately, my docker also decided that appropriate behavior was deleting important system files, so it would be appreciated if someone else oculd verify that these images build and run successfully.
> Deploy different dev and prod docker images
