src/repos/LecturesRepo.js, src/routers/APITypes.js, src/routers/GetLecturesRouter.js
=> GET /courses/:id/lectures/

src/models/Course.js, src/repos/CoursesRepo.js, test/course.test.js, test/course.user.test.js, test/lecture.test.js, test/question.response.test.js
Removed catalogNum and subject field for courses
=> Make Courses more general

src/repos/QuestionsRepo.js, src/routers/GetQuestionsRouter.js
=> GET /lecture/:id/questions/

src/repos/CoursesRepo.js, src/routers/GetCoursesRouter.js
=> GET /organizations/:id/courses/

.travis.yml, test/course.test.js, test/course.user.test.js, test/lecture.test.js, test/organization.test.js, test/question.response.test.js, test/user.test.js
- added .travis.yml file
- project now builds
=> Travis CI file

src/routers/GetOrganizationRouter.js, src/utils/AppDevNodeRouter.js
Thoughts on having this `AppDevNodeRouter` class to fetch nodes?
=> fetch an org

src/routers/Users/GetUserCoursesRouter.js, src/routers/Users/GetUsersRouter.js
Get the courses the user is associated with (either as an admin or student)
=> Get user courses router

src/routers/PostCourseRouter.js
=> POST /organizations/:id/courses/

src/repos/CoursesRepo.js, src/repos/UsersRepo.js, src/routers/Courses/AddStudentsToCourseRouter.js, src/routers/Questions & Responses/PostResponseRouter.js, test/course.user.test.js
- Router for adding students to course
- Repo adjustments
=> Add students to course router

docs/api/Questions.md, src/models/Question.js, src/routers/APITypes.js, src/routers/Questions & Responses/PostQuestionRouter.js
- Updating docs on question/responses
- Clarifying what the `data` field in the `question` model is
=> Specify question type

src/routers/EndLectureRouter.js, src/routers/HelloWorldRouter.js
=> Add health-check 'hello world' endpoint

docs/api/Lectures.md
Clarifying question type for post requests
=> Updated docs for question

src/LectureManager.js, src/repos/LecturesRepo.js, src/routers/Lectures/GetLiveLecturesRouter.js, src/routers/StartLectureRouter.js
Router to get only live lectures from a user's enrollment
- Not sure what the best url is for this router
- Also the router returns a non defined type of node since the typical lecture node doesn't include course name, only id and date time
Let me know if you have any suggestions regarding those two points
=> Get live lectures router

src/routers/APITypes.js, src/utils/AppDevEdgeRouter.js, src/utils/AppDevNodeRouter.js
Small additions for additional type safety and for https://github.com/cuappdev/clicker/pull/47 to work
=> APITypes knows response types too now

package.json, src/API.js, src/server.js
=> Disable HTTP access control on development

src/PollSocket.js
=> live poll sockets

src/PollManager.js, src/PollSocket.js, src/repos/PollsRepo.js, src/routers/EndPollRouter.js, src/routers/GenerateCodeRouter.js, src/routers/Polls/PostPollRouter.js, src/routers/StartPollRouter.js
Routes for:
- Poll code generator
- Starting polls that haven't been created
- Ending polls with option to save/dispose
Check [https://github.com/cuappdev/clicker-api-spec/pull/3](url) for docs on these routes
=> More routers

src/routers/Questions/UpdateQuestionRouter.js
- Wrote UpdateQuestion router file
=> Added 'UpdateQuestion' Router file with my janky dev env

.travis.yml, README.md, package.json, src/db/DbConnection.js
- change db to postgresql
- also updated required env variables
=> postgreSQL

src/models/Poll.js, src/repos/PollsRepo.js, src/routers/Polls/DeletePollRouter.js, src/routers/Polls/PostPollRouter.js, src/routers/Polls/UpdatePollRouter.js, src/routers/StartPollRouter.js, test/poll.test.js, test/question.test.js
- Added deviceId field to poll db object
- Required deviceId param when creating a poll
- Verified deviceId from caller matches poll-associated deviceId in Update/Delete routers
- Updated test files for this change
=> Authentication for poll deleting/updating

.travis.yml, package.json, src/API.js, src/routers/Polls/DeletePollRouter.js, src/routers/Polls/UpdatePollRouter.js, src/routers/Questions/UpdateQuestionRouter.js, src/routers/StartPollRouter.js, test/routes/api.poll.test.js, test/routes/api.question.test.js, test/routes/lib.js
- Makes requests and checks response for API calls
=> Testing routes

src/PollSocket.js
- address issue where if admin disconnects, poll ends (not sure if this fixes it @dantheli )
- results now include question text, and choice
- addresses issues: [74](https://github.com/cuappdev/clicker-backend/issues/74) and [75](https://github.com/cuappdev/clicker-backend/issues/75)
=> Socket fixes

README.md, package-lock.json, package.json
Very basic, just changing readme to use Pollo instead of Clicker and updating Travis badge
=> Renaming clicker to pollo changes

.gitignore, README.md, documentation.yml, package.json, src/SessionManager.js, src/SessionSocket.js, src/models/Base.js, src/models/Draft.js, src/models/Poll.js, src/models/Question.js, src/models/Session.js, src/models/User.js, src/models/UserSession.js, src/repos/DraftsRepo.js, src/repos/PollsRepo.js, src/repos/QuestionsRepo.js, src/repos/SessionsRepo.js, src/repos/UserSessionsRepo.js, src/repos/UsersRepo.js, src/routers/v1/APITypes.js, src/routers/v2/APITypes.js, src/utils/appDevUtils.js, src/utils/constants.js, src/utils/lib.js
- Added tons of docs and comments using JSDoc
- Docs for models, repos, sockets, types, constants, and functions
- HTML support for viewing documentation
=> Added documentation

.eslintignore, .eslintrc.js, src/API.js, src/db/DbConnection.js, src/repos/SessionsRepo.js, test/routes/api.session.test.js
Very straightforward, set length to 100 chars and fixed lines too long
=> Line length set to 100 chars

test/repos/draft.test.js, test/repos/poll.test.js, test/repos/question.test.js, test/repos/session.test.js, test/repos/user.test.js, test/repos/userSession.test.js
Add test cases for repo methods.
=> Add repo tests

src/repos/SessionsRepo.js, src/routers/v2/Polls/GetSessionPollsRouter.js
- Standardize date returned by the server
- Fix get polls error
=> Fix error of blank dates on server; fix get session polls method

.eslintrc, src/routers/v2/Sessions/LeaveSessionRouter.js, test/routes/api.session.test.js
- A route to let members leave poll groups
- Test for route
=> Router for leaving group/session

package-lock.json, package.json, src/routers/v2/Polls/GetSessionPollsRouter.js
- toLocaleString returned different formats when ran locally vs on the server
- toDateString always returns in the format of 'Wed Oct 03 2018'
=> Standardize date when getting polls

src/SessionSocket.js
When an admin connects to the socket, emit the current poll to them
=> Socket message for when admin connects

package-lock.json, src/SessionSocket.js, src/routers/v2/JoinSessionRouter.js
Change free response structure to keep track of the answers that user upvoted
=> Change free response structure

.dockerignore, Dockerfile
Tested by building the Dockerfile, and verifying that it runs properly. 
I copied `.gitignore` into `.dockerignore` since we want to ignore the same files.
=> Move Dockerfile into repo

package-lock.json, package.json, src/API.js
Check the validity of IdToken to increase security
=> Improve google auth handling

src/SessionManager.js, src/SessionSocket.js, src/routers/v2/Sessions/GetAdminSessionsRouter.js, src/routers/v2/Sessions/GetSessionsRouter.js
Added isLive field to indicate whether a session is active/inactive
=> Implement identifier for live session

src/routers/v2/JoinGroupRouter.js, src/routers/v2/StartGroupRouter.js
I missed two group->session endpoints :-(
=> Revert session endpoints

.travis.yml
Travis needs this to deploy to the dev server
=> Add pollo-dev as known host

src/routers/v2/Polls/GetGroupPollsRouter.js, src/routers/v2/Questions/GetGroupQuestionsRouter.js
Fixed the bug where the route combined all polls under one date
=> Fix bug with sorting polls by date

src/routers/v2/APITypes.js, src/routers/v2/JoinGroupRouter.js
I also added trailing commas and alphabetized some stuff
=> Add updatedAt and isLive to JoinGroupRouter

src/GroupSocket.js, src/repos/UserSessionsRepo.js, src/routers/v2/JoinGroupRouter.js, src/routers/v2/Polls/GetGroupPollsRouter.js, src/routers/v2/Questions/GetGroupQuestionsRouter.js
- `server/poll/upvote` will handle both upvoting and un-upvoting if user has already previously upvoted an answer
- the dates in polls and questions sorted by date are now formatted in Unix time in seconds (number instead of string)
- users are added to groups in the database in `/join/session/`, not in the socket
=> Add un-upvoting

src/GroupSocket.js, src/utils/Lib.js
Also alphabetized some imports, renamed some variable names for clarity
=> Fix free response filtering

src/GroupSocket.js
Fix user type `users -> members`
=> Fix user type

src/GroupSocket.js
When user submits a FR answer, upvote count = 1.
User unupvotes the answer, upvote count = 0.
When user tries to upvote again, count stays at 0 but should go up to 1.
=> Fix unupvoting

src/utils/AppDevUtils.js
=> Remove O and 0 from generated codes

src/GroupSocket.js, src/models/Group.js, src/repos/GroupsRepo.js, src/routers/v2/APITypes.js, src/routers/v2/Groups/GetAdminGroupsRouter.js, src/routers/v2/Groups/GetGroupRouter.js, src/routers/v2/Groups/GetGroupsRouter.js, src/routers/v2/Groups/PostGroupRouter.js, src/routers/v2/Groups/UpdateGroupRouter.js, src/routers/v2/JoinGroupRouter.js, src/routers/v2/StartGroupRouter.js, src/routers/v2/swagger.json, test/repos/group.test.js, test/routes/api.group.test.js, test/routes/api.poll.test.js, test/routes/api.question.test.js, test/routes/api.user.test.js
- Initialize `createdAt` with time when poll is created
- Allow profanity filter to be turned on/off
=> Add features to socket

.travis.yml
Before it would only run tests on master or release but this should run tests for all branches now
=> Edit travis config to run tests on every push

package-lock.json, package.json
Only includes packages with updates that don't break test cases
=> Update dependencies with security vulnerabilities

package-lock.json, package.json, src/db/DbConnection.js, src/models/Base.js, src/models/Draft.js, src/models/Group.js, src/models/Poll.js, src/models/Question.js, src/models/User.js, src/models/UserSession.js, src/repos/DraftsRepo.js, src/repos/GroupsRepo.js, src/repos/PollsRepo.js, src/repos/QuestionsRepo.js, src/repos/UserSessionsRepo.js, src/repos/UsersRepo.js
it was a long time coming
had to be done because of security problems in typeorm@`0.1.15`
may need a migration
=> Update to latest TypeORM version

.github/workflows/test.yml
See https://github.com/kq-li/pollo-backend/pull/1
=> Add GitHub action for install/build/test

package-lock.json, test/repos/group.test.js, test/routes/api.group.test.js
Make the group tests able to be run independently of each other.
Tests rewritten to not depend on global state and to all clean up after themselves.
All tests pass consistently and when run individually.
This still needs to be done for the tests of most other parts of the codebase.
Part of #251
=> Decouple group tests

src/routers/v2/CSVGenerator.js, src/routers/v2/Groups/GetCSVRouter.js, src/utils/Constants.js, test/routes/api.group.test.js
Added support for exporting csv files for CMS containing participation grades.
* Created general CSV retrieval route.
* Implemented CMS participation format.
* Expanded testing.
Added significant testing of several poll states and with different dates.
Add support for canvas participation export.
=> Participation CSV exporting for CMS
